//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by d3dWrap.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define ID_FRAME_EXPLORER               128
#define IDR_D3DWRATYPE                  129
#define IDD_FRAME_EXPLORER              130
#define IDD_FRAME_EXPLORER_DEFAULT      131
#define IDD_FRAME_EXPLORER_MAINOBJ      132
#define IDD_FRAME_EXPLORER_DIRLIGHT     133
#define IDD_FRAME_EXPLORER_MAINOBJ_AMBIENTLIGHT 134
#define IDD_FRAME_EXPLORER_MAINOBJ_RENDERING 135
#define IDD_FRAME_EXPLORER_MAINOBJ_FOG  136
#define IDD_FRAME_EXPLORER_SPOT         137
#define IDD_FRAME_EXPLORER_CAMERA       138
#define IDC_TREE_FRAMES                 1000
#define IDC_SLIDER_FRONT                1000
#define IDC_CHECK_ENABLED               1000
#define IDC_CHILD_DLG                   1001
#define IDC_SLIDER_BACK                 1001
#define IDC_LIGHT_ON                    1001
#define IDC_MAINOBJ_TAB                 1002
#define IDC_SLIDER_FIELD                1002
#define IDC_LIGHT_OFF                   1002
#define IDC_SLIDER_RED                  1003
#define IDC_EDIT_FRONT                  1003
#define IDC_FILL_POINTS                 1003
#define IDC_SLIDER_GREEN                1004
#define IDC_SLIDER_RED3                 1004
#define IDC_EDIT_BACK                   1004
#define IDC_FILL_WIREFRAME              1004
#define IDC_SLIDER_BLUE                 1005
#define IDC_SLIDER_RED4                 1005
#define IDC_EDIT_FIELD                  1005
#define IDC_FILL_SOLID                  1005
#define IDC_EDIT_RED                    1006
#define IDC_SHADE_FLAT                  1006
#define IDC_EDIT_GREEN                  1007
#define IDC_EDIT_RED3                   1007
#define IDC_SHADE_GOURAUD               1007
#define IDC_EDIT_BLUE                   1008
#define IDC_EDIT_RED4                   1008
#define IDC_SHADE_PHONG                 1008
#define IDC_SLIDER_UMBRA                1009
#define IDC_SLIDER_RED2                 1009
#define IDC_SLIDER_START                1009
#define IDC_PROJECTION_PERSPECTIVE      1009
#define IDC_EDIT_UMBRA                  1010
#define IDC_SLIDER_GREEN2               1010
#define IDC_EDIT_START                  1010
#define IDC_PROJECTION_ORTHO            1010
#define IDC_SLIDER_PENUMBRA             1011
#define IDC_SLIDER_BLUE2                1011
#define IDC_SLIDER_END                  1011
#define IDC_EDIT_PENUMBRA               1012
#define IDC_EDIT_RED2                   1012
#define IDC_EDIT_END                    1012
#define IDC_SLIDER_RANGE                1013
#define IDC_EDIT_GREEN2                 1013
#define IDC_EDIT_RANGE                  1014
#define IDC_EDIT_BLUE2                  1014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
