//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DSSimplyPlay.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DSSIMPLYPLAY_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDC_PLAY                        1000
#define IDC_STOP                        1001
#define IDC_COUNT                       1002
#define IDC_TIME_DIF                    1003
#define IDM_OPEN                        40001
#define ID_DATEI_BEENDEN                40002
#define IDM_FILE_CLOSE                  40003
#define IDM_FILE_OPEN                   40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
