//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ddSaver.rc
//
#define IDD_DDSAVER_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDC_NULL_CURSOR                 130
#define IDC_EDIT_TEXT                   1001
#define IDC_RADIO_TEXT                  1002
#define IDC_RADIO_TIME                  1003
#define IDC_SLIDER_CELLS                1004
#define IDC_SLIDER_SPEED                1005
#define IDC_COLOR_FORE                  1006
#define IDC_COLOR_BACK                  1007
#define IDC_SELECT_BACK                 1008
#define IDC_SELECT_FORE                 1009
#define IDC_SLIDER_WAIT                 1010
#define IDC_SELECT_FONT                 1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
