//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DSCapture.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DSCAPTURE_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDC_FILE                        1000
#define IDC_FILEOPEN                    1001
#define IDC_ORIGINAL                    1003
#define IDC_PLAY_AND_CAPTURE            1004
#define IDC_ONLY_CAPTURE                1005
#define IDC_PLAY_CAPTURED_RES           1006
#define IDC_START                       1007
#define IDC_STOP                        1008
#define IDC_RADIO5                      1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
