//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DSMineFinder.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DSMINETYPE                  129
#define IDD_3DSOURCE                    130
#define IDC_FILE                        1000
#define IDC_FILEOPEN                    1001
#define IDC_VISIBLE                     1002
#define IDC_RANDSET                     1003
#define IDC_USERSET                     1004
#define IDC_X                           1005
#define IDC_Y                           1006
#define IDC_ANGLE                       1007
#define IDC_ANGL_INN                    1008
#define IDC_ANGL_OUT                    1009
#define IDC_DIST_MIN                    1010
#define IDC_DIST_MAX                    1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
