//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DSDoppler.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_3DSOURCE                    102
#define IDR_MAINFRAME                   128
#define IDR_DSDOPPTYPE                  129
#define IDC_FILE                        1000
#define IDC_FILEOPEN                    1001
#define IDC_VISIBLE                     1002
#define IDC_DIST_MIN                    1010
#define IDC_DIST_MAX                    1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
