#ifndef _D3DDECALOBJ_H_
#define _D3DDECALOBJ_H_

#include "d3dMainObj.h"

/////////////////////////////////////////////////////////////////////////////
// CD3DDecalObj class

class CD3DDecalObj : public CD3DMainObj
  {
  // Construction
  public:
    CD3DDecalObj();
    
    // Attributes
  public:
    
    // Operations
  public:
    
    // Implementation
  public:
    virtual ~CD3DDecalObj();
    
  protected: 
    bool OnCreate(void);
  };

/////////////////////////////////////////////////////////////////////////////

#endif
