#ifndef _D3DMUSHROOMOBJ_H_
#define _D3DMUSHROOMOBJ_H_

#include "d3dMainObj.h"

/////////////////////////////////////////////////////////////////////////////
// CD3DMushroomObj class

class CD3DMushroomObj : public CD3DMainObj
  {
  // Construction
  public:
    CD3DMushroomObj();
    
    // Attributes
  public:
    
    // Operations
  public:
    
    // Implementation
  public:
    virtual ~CD3DMushroomObj();
    
  protected: 
    bool OnCreate(void);
  };

/////////////////////////////////////////////////////////////////////////////

#endif
